name: Reusable Deploy
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
      outputs:
        result:
          description: The result of the deployment operation
          type: string
          value: ${{ jobs.deploy.outputs.outcome}}
    #secrets:
    #some-secret: (should be indented)
    #required: true (should be indented 2x)
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"
      - name: Set Result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
